"""First migration

Revision ID: 282cf8c954b2
Revises: 
Create Date: 2022-11-12 14:17:27.784776

"""
from alembic import op
from json import loads
import sqlalchemy as sa
import os


# revision identifiers, used by Alembic.
revision = '282cf8c954b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    company_table = op.create_table('company',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('website', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('founded', sa.Integer(), nullable=True),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('locality', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=200), nullable=True),
    sa.Column('linkedin_url', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )

    path = os.path.abspath(os.path.dirname(__file__))

    companies_file = open(os.path.join(path, '../data/companies.json'), 'r')
    companies_data = loads(companies_file.read())

    op.bulk_insert(
        company_table,
        companies_data
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company')
    # ### end Alembic commands ###
